/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendientedecajas;

import base.conectar;
import base.usuarios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Elssy
 */
public class Principal extends javax.swing.JFrame {

    usuarios mod;

    /**
     * Creates new form Principal
     */
    final static String URL = "jdbc:mysql://localhost:3306/pCajasMadera?serverTimezone=UTC";
    final static String USUARIO = "root";
    final static String CLAVE = "";

    private static JasperReport reporte;
    private static JasperPrint reporte_generar;
    private static JasperViewer reporte_gui;

    public Principal() {
        initComponents();
        this.setResizable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Imagenes\\icono2.png"));

    }

    public Principal(usuarios mod) {
        initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;

        lbl_nombre_usuario.setText(mod.getNombre());
        lbl_rol.setText(mod.getLast_session());

        if (mod.getId_tipo() == 1) {

        } else if (mod.getId_tipo() == 2) {

            btn_usuario_principal.setEnabled(false);
            btn_exportar_principal.setEnabled(false);
            btn_imprimir_principal.setEnabled(false);
            btn_crear_cajas_prinicpal.setEnabled(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_ver_salidas_principal = new javax.swing.JButton();
        btn_ver_cajas_principal = new javax.swing.JButton();
        btn_ver_pedidos_principal = new javax.swing.JButton();
        btn_ver_entradas_principal = new javax.swing.JButton();
        btn_ver_inventario_principal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_ver_usuarios_principal1 = new javax.swing.JButton();
        btn_crear_cajas_prinicpal = new javax.swing.JButton();
        btn_crear_pedidos_principal = new javax.swing.JButton();
        btn_crear_entrada_prinicipal = new javax.swing.JButton();
        btn_ayuda_principal = new javax.swing.JButton();
        btn_salida_principal = new javax.swing.JButton();
        btn_inventario_principal = new javax.swing.JButton();
        btn_imprimir_principal = new javax.swing.JButton();
        btn_exportar_principal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_usuario_principal = new javax.swing.JButton();
        lbl_nombre_usuario = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        btn_acerdade = new javax.swing.JButton();

        setTitle("Menu Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btn_ver_salidas_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_salidas_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_salidas_principal.setText("VER SALIDAS");
        btn_ver_salidas_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_salidas_principalActionPerformed(evt);
            }
        });

        btn_ver_cajas_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_cajas_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_cajas_principal.setText("VER REGISTROS DE CAJAS");
        btn_ver_cajas_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_cajas_principalActionPerformed(evt);
            }
        });

        btn_ver_pedidos_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_pedidos_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_pedidos_principal.setText("VER PEDIDOS");
        btn_ver_pedidos_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_pedidos_principalActionPerformed(evt);
            }
        });

        btn_ver_entradas_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_entradas_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_entradas_principal.setText("VER ENTRADAS");
        btn_ver_entradas_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_entradas_principalActionPerformed(evt);
            }
        });

        btn_ver_inventario_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_inventario_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_inventario_principal.setText("VER INVENTARIO");
        btn_ver_inventario_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_inventario_principalActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenes.gif"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jButton2.setText("Cerrar Sesión");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_ver_usuarios_principal1.setBackground(new java.awt.Color(51, 51, 51));
        btn_ver_usuarios_principal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ver_usuarios_principal1.setText("VER USUARIOS");
        btn_ver_usuarios_principal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_usuarios_principal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ver_salidas_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_pedidos_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_cajas_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_entradas_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_inventario_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_ver_usuarios_principal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ver_cajas_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver_pedidos_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver_entradas_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver_salidas_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver_usuarios_principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ver_inventario_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_crear_cajas_prinicpal.setBackground(new java.awt.Color(51, 51, 51));
        btn_crear_cajas_prinicpal.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear_cajas_prinicpal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario4.png"))); // NOI18N
        btn_crear_cajas_prinicpal.setText("Crear Registro de Cajas");
        btn_crear_cajas_prinicpal.setToolTipText("");
        btn_crear_cajas_prinicpal.setBorder(null);
        btn_crear_cajas_prinicpal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_cajas_prinicpalActionPerformed(evt);
            }
        });

        btn_crear_pedidos_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_crear_pedidos_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear_pedidos_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos.png"))); // NOI18N
        btn_crear_pedidos_principal.setText("Crear Pedido");
        btn_crear_pedidos_principal.setBorder(null);
        btn_crear_pedidos_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_pedidos_principalActionPerformed(evt);
            }
        });

        btn_crear_entrada_prinicipal.setBackground(new java.awt.Color(51, 51, 51));
        btn_crear_entrada_prinicipal.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear_entrada_prinicipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
        btn_crear_entrada_prinicipal.setText("Crear Nueva Entrada");
        btn_crear_entrada_prinicipal.setBorder(null);
        btn_crear_entrada_prinicipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_entrada_prinicipalActionPerformed(evt);
            }
        });

        btn_ayuda_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_ayuda_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_ayuda_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda.png"))); // NOI18N
        btn_ayuda_principal.setText("Ayuda");
        btn_ayuda_principal.setToolTipText("");
        btn_ayuda_principal.setBorder(null);
        btn_ayuda_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayuda_principalActionPerformed(evt);
            }
        });

        btn_salida_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_salida_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_salida_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
        btn_salida_principal.setText("Nueva Salida");
        btn_salida_principal.setToolTipText("");
        btn_salida_principal.setBorder(null);
        btn_salida_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salida_principalActionPerformed(evt);
            }
        });

        btn_inventario_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_inventario_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_inventario_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invetario.png"))); // NOI18N
        btn_inventario_principal.setText("Iventario");
        btn_inventario_principal.setToolTipText("");
        btn_inventario_principal.setBorder(null);
        btn_inventario_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventario_principalActionPerformed(evt);
            }
        });

        btn_imprimir_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_imprimir_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N
        btn_imprimir_principal.setText("Imprimir Reporte");
        btn_imprimir_principal.setToolTipText("");
        btn_imprimir_principal.setBorder(null);
        btn_imprimir_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_principalActionPerformed(evt);
            }
        });

        btn_exportar_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_exportar_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_exportar_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exportar.png"))); // NOI18N
        btn_exportar_principal.setText("Exportar Reporte");
        btn_exportar_principal.setToolTipText("");
        btn_exportar_principal.setBorder(null);
        btn_exportar_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportar_principalActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N

        btn_usuario_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_usuario_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_usuario_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btn_usuario_principal.setText("Crear Usuario");
        btn_usuario_principal.setToolTipText("");
        btn_usuario_principal.setBorder(null);
        btn_usuario_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario_principalActionPerformed(evt);
            }
        });

        lbl_nombre_usuario.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N

        lbl_rol.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btn_acerdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion.png"))); // NOI18N
        btn_acerdade.setContentAreaFilled(false);
        btn_acerdade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_acerdade.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion _grande.png"))); // NOI18N
        btn_acerdade.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion _grande.png"))); // NOI18N
        btn_acerdade.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_acerdade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_acerdade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acerdadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acerdadeMouseExited(evt);
            }
        });
        btn_acerdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acerdadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_crear_cajas_prinicpal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_crear_pedidos_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btn_crear_entrada_prinicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_acerdade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_ayuda_principal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_imprimir_principal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_exportar_principal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(btn_usuario_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_salida_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_inventario_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_crear_cajas_prinicpal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_crear_pedidos_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_crear_entrada_prinicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_salida_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_inventario_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_usuario_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_imprimir_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_exportar_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_ayuda_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_acerdade, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean TstVentNvoPres = false;
    private void btn_crear_cajas_prinicpalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_cajas_prinicpalActionPerformed

        //Se crea el metodo de la instancia en el JFrame y luego se manda
        //a llamar aqui como get Instance();
        RegistroDeCajas registro = RegistroDeCajas.getInstance();
        registro.setVisible(true);

    }//GEN-LAST:event_btn_crear_cajas_prinicpalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        dispose();
        Login login = Login.getInstance();
        login.setVisible(true);
        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_ver_salidas_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_salidas_principalActionPerformed

        VerSalidas ver_salida = VerSalidas.getInstance();
        ver_salida.setVisible(true);
    }//GEN-LAST:event_btn_ver_salidas_principalActionPerformed

    private void btn_ver_cajas_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_cajas_principalActionPerformed

        VerRegistrosCajas ver_cajas = VerRegistrosCajas.getInstance();
        ver_cajas.setVisible(true);
    }//GEN-LAST:event_btn_ver_cajas_principalActionPerformed

    private void btn_ver_pedidos_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_pedidos_principalActionPerformed

        VerPedidos verpedidos = VerPedidos.getInstance();
        verpedidos.setVisible(true);
    }//GEN-LAST:event_btn_ver_pedidos_principalActionPerformed

    private void btn_ver_entradas_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_entradas_principalActionPerformed

        VerEntradas ver_entradas = VerEntradas.getInstance();
        ver_entradas.setVisible(true);
    }//GEN-LAST:event_btn_ver_entradas_principalActionPerformed

    private void btn_ver_inventario_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_inventario_principalActionPerformed

        VerInventarioTotal inventario = VerInventarioTotal.getInstance();
        inventario.setVisible(true);
    }//GEN-LAST:event_btn_ver_inventario_principalActionPerformed

    private void btn_crear_pedidos_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_pedidos_principalActionPerformed

        RegistroDePedidos pedidos = RegistroDePedidos.getInstance();
        pedidos.setVisible(true);

    }//GEN-LAST:event_btn_crear_pedidos_principalActionPerformed

    private void btn_crear_entrada_prinicipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_entrada_prinicipalActionPerformed

        crearNuevaEntrada entrada = crearNuevaEntrada.getInstance().getInstance();
        entrada.setVisible(true);

    }//GEN-LAST:event_btn_crear_entrada_prinicipalActionPerformed

    private void btn_ayuda_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayuda_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayuda_principalActionPerformed

    private void btn_salida_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salida_principalActionPerformed

        crearNuevaSalida salida = crearNuevaSalida.getInstance();
        salida.setVisible(true);
    }//GEN-LAST:event_btn_salida_principalActionPerformed

    private void btn_inventario_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventario_principalActionPerformed

        Inventario inventario = Inventario.getInstance();
        inventario.setVisible(true);
    }//GEN-LAST:event_btn_inventario_principalActionPerformed

    private void btn_imprimir_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_principalActionPerformed

        Imprimir imprimir = Imprimir.getInstance();
        imprimir.setVisible(true);

    }//GEN-LAST:event_btn_imprimir_principalActionPerformed

    private void btn_exportar_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportar_principalActionPerformed
           // TODO add your handling code here:
           
           FormExportar inv = new FormExportar();
           inv.impresion();
           
           //FormExportar inv = new FormExportar();
           //inv.elemento();
           
           
    }//GEN-LAST:event_btn_exportar_principalActionPerformed

    private void btn_usuario_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario_principalActionPerformed

        RegistroUsuarios usuario = RegistroUsuarios.getInstance().getInstance().getInstance();
        usuario.setVisible(true);
    }//GEN-LAST:event_btn_usuario_principalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int r = JOptionPane.showConfirmDialog(Principal.this, "Seguro que desea salir?", "Salir", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION) {
            System.exit(0);

        } else if (r == JOptionPane.OK_CANCEL_OPTION) {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        }
        // aqui es la panatalla principal
    }//GEN-LAST:event_formWindowClosing

    private void btn_acerdadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acerdadeMouseEntered
      btn_acerdade.setText("Acerca de");
    }//GEN-LAST:event_btn_acerdadeMouseEntered

    private void btn_acerdadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acerdadeMouseExited
       btn_acerdade.setText("");
    }//GEN-LAST:event_btn_acerdadeMouseExited

    private void btn_acerdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acerdadeActionPerformed
        Acercade acerca = Acercade.getInstance();
        acerca.setVisible(true);
    }//GEN-LAST:event_btn_acerdadeActionPerformed

    private void btn_ver_usuarios_principal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_usuarios_principal1ActionPerformed
        VerUsuarios usuario = VerUsuarios.getInstance();
        usuario.setVisible(true);
    }//GEN-LAST:event_btn_ver_usuarios_principal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acerdade;
    private javax.swing.JButton btn_ayuda_principal;
    private javax.swing.JButton btn_crear_cajas_prinicpal;
    private javax.swing.JButton btn_crear_entrada_prinicipal;
    private javax.swing.JButton btn_crear_pedidos_principal;
    private javax.swing.JButton btn_exportar_principal;
    private javax.swing.JButton btn_imprimir_principal;
    private javax.swing.JButton btn_inventario_principal;
    private javax.swing.JButton btn_salida_principal;
    private javax.swing.JButton btn_usuario_principal;
    private javax.swing.JButton btn_ver_cajas_principal;
    private javax.swing.JButton btn_ver_entradas_principal;
    private javax.swing.JButton btn_ver_inventario_principal;
    private javax.swing.JButton btn_ver_pedidos_principal;
    private javax.swing.JButton btn_ver_salidas_principal;
    private javax.swing.JButton btn_ver_usuarios_principal1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_nombre_usuario;
    private javax.swing.JLabel lbl_rol;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
    Connection cn = cc.conexion();
    
    
    /*public void impresion(){
       String imagen = "base\\Reporte_Inventario_MP.xls";
        Ruta = System.getProperty("user.dir") + "\\" + imagen;
        File file = new File(Ruta);
        ExportarExcel excel = new ExportarExcel(Inventario,file,"tb_tablas");
        excel.export();
    }*/

}
