/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendientedecajas;

import base.DataBase;
import base.conectar;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Background;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Elssy
 */
public class RegistroDeCajas extends javax.swing.JFrame {

    final static String URL = "jdbc:mysql://localhost:3306/pCajasMadera?useSSL=true";
    final static String USUARIO = "root";
    final static String CLAVE = "";
    private static RegistroDeCajas myInstance;

    /**
     * Creates new form RegistroDeCajas
     */
    //VARIABLE PARA EL BUSCADOOR
    TableRowSorter trs;
    //Variable Place HOLDER
    PlaceHolder holder;

    public RegistroDeCajas() {
        initComponents();
        setLocationRelativeTo(null);
        mostrardatos("");
        txt_id_registro.setText(DataBase.extraerIdMaxCajas());
        tbregistro_cajas.setRowSorter(trs);
        
        holder = new PlaceHolder(txtbuscar_registro, "Marca, Vitola, Nombre, Capa");
        holder = new PlaceHolder(txtmarca_registro, "Nombre de la marca");
        holder = new PlaceHolder(txtvitola_registro, "Escriba la vitola");
        holder = new PlaceHolder(txtnombre_registro, "Escriba el nombre");
        holder = new PlaceHolder(txtcapa_registro, "Nombre de la capa");
        holder = new PlaceHolder(txtempaque_registro, "Escriba el tipo de empaque");
        holder = new PlaceHolder(txtinventarioInicial_registro, "0000");
        
        

    }

    private void close() {
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //DefaultTableModel dm;

    /*private void filtro(String consulta, JTable jtableBuscar){
        dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
}*/
    void mostrardatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel() {

            //Quitar edición de las tablas
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("Id");
        modelo.addColumn("Marca");
        modelo.addColumn("Vitola");
        modelo.addColumn("Nombre");
        modelo.addColumn("Capa");
        modelo.addColumn("Tipo de Empaque");
        modelo.addColumn("Iventario Inicial");
        tbregistro_cajas.setModel(modelo);
        tbregistro_cajas.getTableHeader().setReorderingAllowed(false);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM registroCajas";
        } else {
            sql = "SELECT * FROM registroCajas WHERE marca LIKE '%" + valor + "%'";
        }

        String[] datos = new String[7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);

                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                modelo.addRow(datos);
            }
            tbregistro_cajas.setModel(modelo);
            tbregistro_cajas.getTableHeader().setReorderingAllowed(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistroDeCajas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtvitola_registro = new javax.swing.JTextField();
        txtmarca_registro = new javax.swing.JTextField();
        txtnombre_registro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcapa_registro = new javax.swing.JTextField();
        txtempaque_registro = new javax.swing.JTextField();
        txtinventarioInicial_registro = new javax.swing.JTextField();
        btn_guardar_caja = new javax.swing.JButton();
        btn_actualizar_registro = new javax.swing.JButton();
        txt_id_registro = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        txtbuscar_registro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnmostrar_registro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbregistro_cajas = new javax.swing.JTable();

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Cajas");
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Cajas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tipo de Empaque:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vitola");

        txtvitola_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvitola_registroActionPerformed(evt);
            }
        });

        txtmarca_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarca_registroActionPerformed(evt);
            }
        });

        txtnombre_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre_registroActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Capa:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Inventario Inicial:");

        btn_guardar_caja.setBackground(new java.awt.Color(51, 51, 51));
        btn_guardar_caja.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disquete.png"))); // NOI18N
        btn_guardar_caja.setText("Guardar");
        btn_guardar_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_cajaActionPerformed(evt);
            }
        });

        btn_actualizar_registro.setBackground(new java.awt.Color(51, 51, 51));
        btn_actualizar_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btn_actualizar_registro.setText("Actualizar");
        btn_actualizar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_registroActionPerformed(evt);
            }
        });

        txt_id_registro.setEditable(false);
        txt_id_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_registroActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(51, 51, 51));
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmarca_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvitola_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_registro)))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcapa_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtempaque_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtinventarioInicial_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar_registro)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcapa_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarca_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempaque_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvitola_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinventarioInicial_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar_registro)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar_caja))
                .addGap(18, 18, 18))
        );

        txtbuscar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_registroActionPerformed(evt);
            }
        });
        txtbuscar_registro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscar_registroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscar_registroKeyTyped(evt);
            }
        });

        jLabel8.setText("Buscar:");

        btnmostrar_registro.setText("Mostrar Todos los Datos");
        btnmostrar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrar_registroActionPerformed(evt);
            }
        });

        tbregistro_cajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbregistro_cajas.setComponentPopupMenu(jPopupMenu2);
        jScrollPane1.setViewportView(tbregistro_cajas);
        if (tbregistro_cajas.getColumnModel().getColumnCount() > 0) {
            tbregistro_cajas.getColumnModel().getColumn(0).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(1).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(2).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(3).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(4).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(5).setResizable(false);
            tbregistro_cajas.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbuscar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnmostrar_registro)
                .addGap(0, 400, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmostrar_registro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvitola_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvitola_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvitola_registroActionPerformed

    private void txtnombre_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_registroActionPerformed
    //Metodo para limpiar campos.
    private void limpiar() {
        txt_id_registro.setText(null);
        txtmarca_registro.setText(null);
        txtvitola_registro.setText(null);
        txtnombre_registro.setText(null);
        txtcapa_registro.setText(null);
        txtempaque_registro.setText(null);
        txtinventarioInicial_registro.setText(null);
    }
    private void btn_guardar_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_cajaActionPerformed
        // TODO add your handling code here:
        
        if(txtmarca_registro.getText().isEmpty() || txtvitola_registro.getText().isEmpty() || txtnombre_registro.getText().isEmpty()
                || txtcapa_registro.getText().isEmpty() || txtempaque_registro.getText().isEmpty() || txtinventarioInicial_registro.getText().isEmpty()
         ){
           
            JOptionPane.showMessageDialog(this, "Por favor llenar todos los campos.");
        }else{
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO registroCajas (marca,vitola,nombre,capa,tipo_empaque,invent_inicial) VALUES (?,?,?,?,?,?)");

            //pst.setString(1, txt_id_registro.getText());
            pst.setString(1, txtmarca_registro.getText());
            pst.setString(2, txtvitola_registro.getText());
            pst.setString(3, txtnombre_registro.getText());
            pst.setString(4, txtcapa_registro.getText());
            pst.setString(5, txtempaque_registro.getText());
            pst.setString(6, txtinventarioInicial_registro.getText());

            pst.executeUpdate();
            mostrardatos("");
            limpiar();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
        
        }
    }//GEN-LAST:event_btn_guardar_cajaActionPerformed

    private void btnmostrar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrar_registroActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
    }//GEN-LAST:event_btnmostrar_registroActionPerformed

    private void txt_id_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_registroActionPerformed

    private void btn_actualizar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_registroActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = cn.prepareStatement("UPDATE registroCajas SET marca='" + txtmarca_registro.getText() + "',vitola='" + txtvitola_registro.getText() + ""
                    + "',nombre='" + txtnombre_registro.getText() + "',capa='" + txtcapa_registro.getText() + "',tipo_empaque='" + txtempaque_registro.getText() + "',invent_inicial='" + txtinventarioInicial_registro.getText() + "' WHERE id_caja='" + txt_id_registro.getText() + "'");
            pst.executeUpdate();
            mostrardatos("");
            limpiar();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }

    }//GEN-LAST:event_btn_actualizar_registroActionPerformed

    private void txtbuscar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_registroActionPerformed
        // TODO add your handling code here:
        //mostrardatos(txtbuscar_registro.getText());
    }//GEN-LAST:event_txtbuscar_registroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int fila = tbregistro_cajas.getSelectedRow();
        if (fila >= 0) {
            txt_id_registro.setText(tbregistro_cajas.getValueAt(fila, 0).toString());
            txtmarca_registro.setText(tbregistro_cajas.getValueAt(fila, 1).toString());
            txtvitola_registro.setText(tbregistro_cajas.getValueAt(fila, 2).toString());
            txtnombre_registro.setText(tbregistro_cajas.getValueAt(fila, 3).toString());
            txtcapa_registro.setText(tbregistro_cajas.getValueAt(fila, 4).toString());
            txtempaque_registro.setText(tbregistro_cajas.getValueAt(fila, 5).toString());
            txtinventarioInicial_registro.setText(tbregistro_cajas.getValueAt(fila, 6).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No Seleciono Fila");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        dispose();


    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txtbuscar_registroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar_registroKeyReleased
        // TODO add your handling code here:         
    }//GEN-LAST:event_txtbuscar_registroKeyReleased

    private void txtbuscar_registroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar_registroKeyTyped
        // TODO add your handling code here:
        //METODO PARA BUSCAR
        txtbuscar_registro.setText(txtbuscar_registro.getText().replaceAll("( )+", " "));
        //Validaciones.Space(txt_buscar_pedidos.getText().length(), evt);        
        DefaultTableModel cajas = (DefaultTableModel) tbregistro_cajas.getModel();
        txtbuscar_registro.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtbuscar_registro.getText(), 1, 2, 3, 4));
                //trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar_ver_cajas.getText(), 3));

                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }

        });
        trs = new TableRowSorter(cajas);
        tbregistro_cajas.setRowSorter(trs);
    }//GEN-LAST:event_txtbuscar_registroKeyTyped

    private void txtmarca_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarca_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarca_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeCajas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar_registro;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar_caja;
    private javax.swing.JButton btnmostrar_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbregistro_cajas;
    private javax.swing.JTextField txt_id_registro;
    private javax.swing.JTextField txtbuscar_registro;
    private javax.swing.JTextField txtcapa_registro;
    private javax.swing.JTextField txtempaque_registro;
    private javax.swing.JTextField txtinventarioInicial_registro;
    private javax.swing.JTextField txtmarca_registro;
    private javax.swing.JTextField txtnombre_registro;
    private javax.swing.JTextField txtvitola_registro;
    // End of variables declaration//GEN-END:variables
    conectar cc = new conectar();
    Connection cn = cc.conexion();

    //Metodo para que solo se abra una sola pantalla.
    public static RegistroDeCajas getInstance() {
        if (myInstance == null) {
            myInstance = new RegistroDeCajas();
        }
        return myInstance;
    }

}
