/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendientedecajas;

import base.DataBase;
import base.conectar;
import com.placeholder.PlaceHolder;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Elssy
 */

public class VerPedidos extends javax.swing.JFrame {

    /**
     * Creates new form VerPedidos
     */
    
      final static String URL = "jdbc:mysql://localhost:3306/pCajasMadera?useSSL=true";
	final static String USUARIO = "root";
	final static String CLAVE = "";
        
        
          //Variable de instancia   
      private static VerPedidos myInstance;
        TableRowSorter trs;
      //Variable Place HOLDER
      PlaceHolder holder;
    public VerPedidos() {
        initComponents();
        setLocationRelativeTo(null);
        mostrardatos_verpedidos("");
        tb_ver_pedidos.setRowSorter(trs);
        //PARA USAR EL PLACEHOLDER
        holder = new PlaceHolder(txt_ver_pedidos, "Marca, Vitola, Nombre, Capa");
        //PARA AÑADIR EL FOCUS A OTRO COMPONENTE
        btn_regresar_pedidos_principal.requestFocus();
        
    }
    
    void mostrardatos_verpedidos(String valor){
    DefaultTableModel modeloverpedidos= new DefaultTableModel(){

		//Quitar edición de las tablas
	    @Override
	    public boolean isCellEditable(int row, int column) {
	        return false;
	    }
	};	
    
    modeloverpedidos.addColumn("Id");
      //modeloverpedidos.addColumn("Id");
    modeloverpedidos.addColumn("Marca");
    modeloverpedidos.addColumn("Vitola");
    modeloverpedidos.addColumn("Nombre");
    modeloverpedidos.addColumn("Capa");
    modeloverpedidos.addColumn("Tipo de Empaque");
    modeloverpedidos.addColumn("Iventario Inicial");
    modeloverpedidos.addColumn("Enero");
    modeloverpedidos.addColumn("Febrero");
    modeloverpedidos.addColumn("Marzo");
    modeloverpedidos.addColumn("Abril");
    modeloverpedidos.addColumn("Mayo");
    modeloverpedidos.addColumn("Junio");
    modeloverpedidos.addColumn("Julio");
     modeloverpedidos.addColumn("Agosto");
    modeloverpedidos.addColumn("Septiembre");
    modeloverpedidos.addColumn("Octubre");
    modeloverpedidos.addColumn("Noviembre");
    modeloverpedidos.addColumn("Diciembre");
    modeloverpedidos.addColumn("Observación");
    modeloverpedidos.addColumn("Total Ordenes");
    tb_ver_pedidos.setModel(modeloverpedidos);
    
    modeloverpedidos = new DefaultTableModel(DataBase.cargarpedidos(), columnas_verpedidos){

		//Quitar edición de las tablas
	    @Override
	    public boolean isCellEditable(int row, int column) {
	        return false;
	    }
    };
    tb_ver_pedidos.setModel(modeloverpedidos);
    //NO MOVER LAS COLUMNAS DE LA TABLA
        tb_ver_pedidos.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ver_pedidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ver_pedidos = new javax.swing.JTable();
        btn_regresar_pedidos_principal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Buscar:");

        txt_ver_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ver_pedidosActionPerformed(evt);
            }
        });
        txt_ver_pedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ver_pedidosKeyTyped(evt);
            }
        });

        tb_ver_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_ver_pedidos);

        btn_regresar_pedidos_principal.setBackground(new java.awt.Color(51, 51, 51));
        btn_regresar_pedidos_principal.setForeground(new java.awt.Color(255, 255, 255));
        btn_regresar_pedidos_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-correcta.png"))); // NOI18N
        btn_regresar_pedidos_principal.setText("Regresar");
        btn_regresar_pedidos_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresar_pedidos_principalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ver_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                .addComponent(btn_regresar_pedidos_principal)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ver_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar_pedidos_principal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar_pedidos_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresar_pedidos_principalActionPerformed
        // TODO add your handling code here:
         dispose(); 
         
    }//GEN-LAST:event_btn_regresar_pedidos_principalActionPerformed

    private void txt_ver_pedidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ver_pedidosKeyTyped
        // TODO add your handling code here:
        txt_ver_pedidos.setText(txt_ver_pedidos.getText().replaceAll("( )+", " "));
        //Validaciones.Space(txt_buscar_pedidos.getText().length(), evt);        
        DefaultTableModel verpedidos = (DefaultTableModel) tb_ver_pedidos.getModel();
        txt_ver_pedidos.addKeyListener(new KeyAdapter() { 

            @Override
            public void keyReleased(KeyEvent ke) {   
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txt_ver_pedidos.getText(), 1, 2, 3, 4));
                //trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar_ver_cajas.getText(), 3));
                
                
                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }
        
        
        });
        trs = new TableRowSorter(verpedidos);
        tb_ver_pedidos.setRowSorter(trs);
    }//GEN-LAST:event_txt_ver_pedidosKeyTyped

    private void txt_ver_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ver_pedidosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_ver_pedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar_pedidos_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ver_pedidos;
    private javax.swing.JTextField txt_ver_pedidos;
    // End of variables declaration//GEN-END:variables
conectar cc= new conectar();
   Connection cn= cc.conexion();
   
   private DefaultTableModel modelocaja;
   
    private final String columnas_verpedidos []={"Id","Marca","Vitola", "Nombre", "Capa","Tipo de Empaque","Inventario Inicial","Enero","Febrero","Marzo","Abril","Mayo","Junio",
    "Julio","Agosto", "Septiembre","Octubre", "Noviembre","Diciembre","Observación","Total Orden"};
    
    public static VerPedidos getInstance()
	{ 
	if (myInstance == null) 
	myInstance = new VerPedidos(); 
	return myInstance; 
	}
    
  
}
