/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendientedecajas;

import base.DataBase;
import base.conectar;
import com.placeholder.PlaceHolder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Elssy
 */
public class VerRegistrosCajas extends javax.swing.JFrame {

    /**
     * Creates new form VerRegistrosCajas
     */
    final static String URL = "jdbc:mysql://localhost:3306/pCajasMadera?useSSL=true";
    final static String USUARIO = "root";
    final static String CLAVE = "";
    static JTable table = new JTable() {

        //Quitar edición de las tablas
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    //Variable de instancia   
    private static VerRegistrosCajas myInstance;
    TableRowSorter trs;
    //Variable Place HOLDER
    PlaceHolder holder;

    public VerRegistrosCajas() {
        initComponents();
        setLocationRelativeTo(null);
        mostrardatos_vercajas("");
        tb_ver_cajas.setRowSorter(trs);
        //CODIGO PARA HACER PLACE HOLDER
        holder = new PlaceHolder(txtbuscar_ver_cajas, "Marca, Vitola, Nombre, Capa");
        //PARA AÑADIR EL FOCUS A OTRO COMPONENTE
        btn_regresar_vercajas.requestFocus();
        tb_ver_cajas.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void mostrardatos_vercajas(String valor) {
        DefaultTableModel modelo = new DefaultTableModel() {

            //Quitar edición de las tablas
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("Id");
        modelo.addColumn("Marca");
        modelo.addColumn("Vitola");
        modelo.addColumn("Nombre");
        modelo.addColumn("Capa");
        modelo.addColumn("Tipo de Empaque");
        modelo.addColumn("Iventario Inicial");
        tb_ver_cajas.setModel(modelo);

        modelo = new DefaultTableModel(DataBase.cargarcajas(), columnas_vercajas) {

            //Quitar edición de las tablas
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_ver_cajas.setModel(modelo);
        tb_ver_cajas.getTableHeader().setReorderingAllowed(false);

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ver_cajas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar_ver_cajas = new javax.swing.JTextField();
        btn_regresar_vercajas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        tb_ver_cajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_ver_cajas);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Buscar:");
        jLabel1.setToolTipText("");

        txtbuscar_ver_cajas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtbuscar_ver_cajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_ver_cajasActionPerformed(evt);
            }
        });
        txtbuscar_ver_cajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscar_ver_cajasKeyTyped(evt);
            }
        });

        btn_regresar_vercajas.setBackground(new java.awt.Color(51, 51, 51));
        btn_regresar_vercajas.setForeground(new java.awt.Color(255, 255, 255));
        btn_regresar_vercajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-correcta.png"))); // NOI18N
        btn_regresar_vercajas.setText("Regresar");
        btn_regresar_vercajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresar_vercajasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar_ver_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(btn_regresar_vercajas)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscar_ver_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar_vercajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar_vercajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresar_vercajasActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_regresar_vercajasActionPerformed

    private void txtbuscar_ver_cajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar_ver_cajasKeyTyped
        // TODO add your handling code here:
        //METODO PARA BUSCAR
        txtbuscar_ver_cajas.setText(txtbuscar_ver_cajas.getText().replaceAll("( )+", " "));
        //Validaciones.Space(txt_buscar_pedidos.getText().length(), evt);        
        DefaultTableModel verpedidos = (DefaultTableModel) tb_ver_cajas.getModel();
        txtbuscar_ver_cajas.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtbuscar_ver_cajas.getText(), 1, 2, 3, 4));
                //trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtbuscar_ver_cajas.getText(), 3));

                super.keyReleased(ke); //To change body of generated methods, choose Tools | Templates.
            }

        });
        trs = new TableRowSorter(verpedidos);
        tb_ver_cajas.setRowSorter(trs);
    }//GEN-LAST:event_txtbuscar_ver_cajasKeyTyped

    private void txtbuscar_ver_cajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_ver_cajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscar_ver_cajasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerRegistrosCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerRegistrosCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerRegistrosCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerRegistrosCajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerRegistrosCajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar_vercajas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ver_cajas;
    private javax.swing.JTextField txtbuscar_ver_cajas;
    // End of variables declaration//GEN-END:variables

    conectar cc = new conectar();
    Connection cn = cc.conexion();

    private DefaultTableModel modelocaja;

    private final String columnas_vercajas[] = {"Id", "Marca", "Vitola", "Nombre", "Capa", "Tipo de Empaque", "Inventario Inicial"};

    public static VerRegistrosCajas getInstance() {
        if (myInstance == null) {
            myInstance = new VerRegistrosCajas();
        }
        return myInstance;
    }
}
